// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"support/index.mdx": () => import("../content/client-keeper/support/index.mdx?collection=docs"), "support/contacts/adding-contacts.mdx": () => import("../content/client-keeper/support/contacts/adding-contacts.mdx?collection=docs"), "support/contacts/contact-groups.mdx": () => import("../content/client-keeper/support/contacts/contact-groups.mdx?collection=docs"), "support/contacts/index.mdx": () => import("../content/client-keeper/support/contacts/index.mdx?collection=docs"), "support/contacts/recurring-followups.mdx": () => import("../content/client-keeper/support/contacts/recurring-followups.mdx?collection=docs"), "support/faq/billing.mdx": () => import("../content/client-keeper/support/faq/billing.mdx?collection=docs"), "support/faq/index.mdx": () => import("../content/client-keeper/support/faq/index.mdx?collection=docs"), "support/faq/troubleshooting.mdx": () => import("../content/client-keeper/support/faq/troubleshooting.mdx?collection=docs"), "support/getting-started/creating-account.mdx": () => import("../content/client-keeper/support/getting-started/creating-account.mdx?collection=docs"), "support/getting-started/export-data.mdx": () => import("../content/client-keeper/support/getting-started/export-data.mdx?collection=docs"), "support/getting-started/first-client.mdx": () => import("../content/client-keeper/support/getting-started/first-client.mdx?collection=docs"), "support/getting-started/index.mdx": () => import("../content/client-keeper/support/getting-started/index.mdx?collection=docs"), "support/getting-started/login-setup.mdx": () => import("../content/client-keeper/support/getting-started/login-setup.mdx?collection=docs"), "support/features/client-management.mdx": () => import("../content/client-keeper/support/features/client-management.mdx?collection=docs"), "support/features/deals-pipeline.mdx": () => import("../content/client-keeper/support/features/deals-pipeline.mdx?collection=docs"), "support/features/index.mdx": () => import("../content/client-keeper/support/features/index.mdx?collection=docs"), "support/features/myra-ai.mdx": () => import("../content/client-keeper/support/features/myra-ai.mdx?collection=docs"), "support/features/notes.mdx": () => import("../content/client-keeper/support/features/notes.mdx?collection=docs"), "support/features/reminders.mdx": () => import("../content/client-keeper/support/features/reminders.mdx?collection=docs"), "support/features/todos.mdx": () => import("../content/client-keeper/support/features/todos.mdx?collection=docs"), }),
};
export default browserCollections;